/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b8c3ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#434656",
        "surface-container-high": "#dde9ff",
        "on-secondary-container": "#5c647a",
        "on-primary-container": "#efefff",
        "on-tertiary-container": "#f1eeff",
        "secondary": "#565e74",
        "tertiary-container": "#585be6",
        "primary": "#0040e0",
        "tertiary-fixed": "#e1e0ff",
        "surface-variant": "#d5e3fd",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#07006c",
        "primary-fixed-dim": "#b8c3ff",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#ebf1ff",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-background": "#0d1c2f",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-surface": "#0d1c2f",
        "on-secondary-fixed": "#131b2e",
        "background": "#f8f9ff",
        "outline": "#747688",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface-container": "#e6eeff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#124af0",
        "secondary-container": "#dae2fd",
        "surface-container-highest": "#d5e3fd",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001356",
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#bec6e0",
        "primary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-dim": "#ccdbf4",
        "on-secondary-fixed-variant": "#3f465c",
        "primary-container": "#2e5bff",
        "outline-variant": "#c4c5d9",
        "on-primary-fixed-variant": "#0035be",
        "tertiary": "#3e3fcc",
        "emerald-match": "#10B981",
        "indigo-apply": "#4F46E5"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
